// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DBFinanzasContext))]
    [Migration("20251115212054_AddRolPersona")]
    partial class AddRolPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MonedaBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("UX_Activos_Symbol");

                    b.ToTable("Activos", (string)null);
                });

            modelBuilder.Entity("Domain.CedearRatio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CedearId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UsAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CedearId")
                        .IsUnique();

                    b.HasIndex("UsAssetId")
                        .IsUnique();

                    b.HasIndex("CedearId", "UsAssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_CedearRatios");

                    b.ToTable("CedearRatios", (string)null);
                });

            modelBuilder.Entity("Domain.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.ToTable("Cotizaciones", (string)null);
                });

            modelBuilder.Entity("Domain.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades", (string)null);
                });

            modelBuilder.Entity("Domain.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FechaOperacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaOperacion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Operaciones", (string)null);
                });

            modelBuilder.Entity("Domain.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("CodigoIso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<bool>("EsArgentina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIso2")
                        .IsUnique()
                        .HasDatabaseName("UX_Paises_Iso2");

                    b.HasIndex("CodigoIso3")
                        .IsUnique()
                        .HasDatabaseName("UX_Paises_Iso3");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("Domain.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsResidenteArgentina")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocalidadResidenciaId")
                        .HasColumnType("int");

                    b.Property<int>("NacionalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PaisResidenciaId")
                        .HasColumnType("int");

                    b.Property<byte>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LocalidadResidenciaId");

                    b.HasIndex("NacionalidadId");

                    b.HasIndex("PaisResidenciaId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("Domain.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias", (string)null);
                });

            modelBuilder.Entity("Domain.CedearRatio", b =>
                {
                    b.HasOne("Domain.Activo", "Cedear")
                        .WithOne("CedearRatioCedear")
                        .HasForeignKey("Domain.CedearRatio", "CedearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CedearRatios_Cedear");

                    b.HasOne("Domain.Activo", "UsAsset")
                        .WithOne("CedearRatioUsAsset")
                        .HasForeignKey("Domain.CedearRatio", "UsAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CedearRatios_UsAsset");

                    b.Navigation("Cedear");

                    b.Navigation("UsAsset");
                });

            modelBuilder.Entity("Domain.Cotizacion", b =>
                {
                    b.HasOne("Domain.Activo", "Activo")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cotizaciones_Activo");

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("Domain.Localidad", b =>
                {
                    b.HasOne("Domain.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Localidades_Provincia");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Domain.Operacion", b =>
                {
                    b.HasOne("Domain.Activo", "Activo")
                        .WithMany("Operaciones")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Operaciones_Activo");

                    b.HasOne("Domain.Persona", "Persona")
                        .WithMany("Operaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Operaciones_Persona");

                    b.Navigation("Activo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Persona", b =>
                {
                    b.HasOne("Domain.Localidad", "LocalidadResidencia")
                        .WithMany("PersonasResidencia")
                        .HasForeignKey("LocalidadResidenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Personas_LocalidadResidencia");

                    b.HasOne("Domain.Pais", "Nacionalidad")
                        .WithMany("PersonasNacionalidad")
                        .HasForeignKey("NacionalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Personas_PaisNacionalidad");

                    b.HasOne("Domain.Pais", "PaisResidencia")
                        .WithMany("PersonasResidencia")
                        .HasForeignKey("PaisResidenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Personas_PaisResidencia");

                    b.Navigation("LocalidadResidencia");

                    b.Navigation("Nacionalidad");

                    b.Navigation("PaisResidencia");
                });

            modelBuilder.Entity("Domain.Provincia", b =>
                {
                    b.HasOne("Domain.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Provincias_Pais");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Domain.Activo", b =>
                {
                    b.Navigation("CedearRatioCedear");

                    b.Navigation("CedearRatioUsAsset");

                    b.Navigation("Cotizaciones");

                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("Domain.Localidad", b =>
                {
                    b.Navigation("PersonasResidencia");
                });

            modelBuilder.Entity("Domain.Pais", b =>
                {
                    b.Navigation("PersonasNacionalidad");

                    b.Navigation("PersonasResidencia");

                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Domain.Persona", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("Domain.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });
#pragma warning restore 612, 618
        }
    }
}
